sudo: required
services:
  - docker

before_install:
  - docker build -t nil123456/docker-react -f Dockerfile.dev .

install: travis_wait mvn install

script:
  - docker run nil123456/docker-react npm run test -- --coverage  